worker_processes 5;
daemon off;

worker_rlimit_nofile 8192;

events {
  worker_connections  4096;
}

http {
    include /etc/nginx/mime.types;
    include /etc/nginx/fastcgi.conf;
    default_type application/octet-stream;
    log_format   main '$remote_addr - $remote_user [$time_local]  $status '
        '"$request" $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';
    access_log /dev/stdout;
    error_log /dev/stdout;
    sendfile     on;
    keepalive_timeout 65;

    # INCREMENTADO EL LÍMITE DE SUBIDA DE NGINX A 500MB
    client_max_body_size 500M;

    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name _;
        root /app;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }
    }
}
