CREATE TABLE IF NOT EXISTS images (
    id SERIAL PRIMARY KEY,
    unique_id VARCHAR(21) UNIQUE NOT NULL,
    filename VARCHAR(255) NOT NULL,
    url TEXT NOT NULL,
    size INTEGER NOT NULL,
    mime_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
